# eslint configuration
parser: babel-eslint
parserOptions:
  ecmaVersion: 6
  sourceType: module
  ecmaFeatures:
    # support redux shallow copy
    experimentalObjectRestSpread: true
env:
  es6: true
  node: true
  jasmine: true
  mocha: true
extends:
  - 'eslint:recommended'
rules:
  indent:
    - error
    - 2
    - SwitchCase: 1
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
    - allowTemplateLiterals: true
  semi:
    - error
    - always
